//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace openlocally.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("openlocally.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Do you want to open it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_YOU_WANT_TO_OPEN {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File or Folder &apos;{0}&apos; does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_OR_FOLDER_NOT_EXIST {
            get {
                return ResourceManager.GetString("FILE_OR_FOLDER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local path for &apos;{0}&apos; is not found in this machine ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOCAL_PATH_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOCAL_PATH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More than one argument に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MORE_THAN_1_ARGUMENTS {
            get {
                return ResourceManager.GetString("MORE_THAN_1_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_ARGUMENTS {
            get {
                return ResourceManager.GetString("NO_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path &apos;{0}&apos; is local path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PATH_IS_ORIGINALLY_LOCAL {
            get {
                return ResourceManager.GetString("PATH_IS_ORIGINALLY_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not hosted on this machine. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PATH_NOT_HOSTED {
            get {
                return ResourceManager.GetString("PATH_NOT_HOSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path is resolved to &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PATH_RESOLVED_DO_YOU_WANT_TO_OPEN {
            get {
                return ResourceManager.GetString("PATH_RESOLVED_DO_YOU_WANT_TO_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program &apos;{0}&apos; does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROGRAM_NOT_EXIST {
            get {
                return ResourceManager.GetString("PROGRAM_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server is null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SERVER_NULL {
            get {
                return ResourceManager.GetString("SERVER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serve and Share are null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SERVERANDSHARE_NULL {
            get {
                return ResourceManager.GetString("SERVERANDSHARE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShareCollection is null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHARECOLLECTION_NULL {
            get {
                return ResourceManager.GetString("SHARECOLLECTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too many arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOO_MANY_ARGUMENTS {
            get {
                return ResourceManager.GetString("TOO_MANY_ARGUMENTS", resourceCulture);
            }
        }
    }
}
